### ISSUE TITLE
Arrays util facing TS2370

### ISSUE THREAD

**Issue by i7i5** [SchweizerischeBundesbahnen/scion-toolkit#48]
## Describe the bug
We are devloping a poc for sbb using latest Angular 11 and typescript version ~4.1.2 but also tried 4.0.5. Our frontend doesn't compile because of the following error:
```
Error: node_modules/@scion/toolkit/util/arrays.util.d.ts:42:25 - error TS2370: A rest parameter must be of an array type.

42 static intersect<T>(...arrays: T[][] | undefined): T[] | undefined;
```

## To Reproduce

1. create an Angular 11 project
2. Use typescript version 4+
3. Use latest scion toolkit version

## Expected behavior
compilation works

## Screenshots
![image](https://user-images.githubusercontent.com/9058776/110352414-34f51b80-8036-11eb-81e9-8037beba43e7.png)

## Solution
change
`public static intersect<T>(...arrays: T[][] | undefined): T[] | undefined {`
to
`public static intersect<T>([...arrays]: T[][] | undefined): T[] | undefined {`

I really wanted to contribute this one liner but `before-push` fails due to linting errors in `app.po.ts` and `app.e2e-spec.ts`. After fixing them this command crashes with several `error NG6002`. Pls could you provide the fix?

BR
i7i5

**Comment by danielwiehl** [comment]
Thank you, @i7i5, for filing this issue. It is related to issue #42, which is at the top of our backlog.

Since Angular 11 (or even 10), the Angular CLI scaffolds projects with strict type checking enabled. In the meantime, as a workaround, please disable strict type checking as follows:

In your `tsconfig.json`, set the `strict` flag to `false`, or more specifically, set the `strictNullChecks` flag to `false`. Note that we have not yet compiled SCION projects with all strict flags enabled, so you may encounter further violations if only disabling `strictNullChecks`. Therefore, we recommend disabling all strict type checking with `"strict": false` until issue #42 is fixed.

If you have any further questions or need assistance regarding the PoC, please let us know.

**Comment by i7i5** [comment]
Hello @danielwiehl, thank you for the fast answer, I'll try this tomorrow. :)

Since this is obviously a douplicate of #42, I close this one.

**Comment by danielwiehl** [comment]
@i7i5, you wrote that you experienced some problems when running the command `before-push`:

**@NG6002**
It turned out that this error only occurs when starting the testing app without first compiling the toolkit libraries to the Ivy format. Then, the Angular CLI runs `ngcc` on the fly, which, for whatever reason, does not wait for all packages to finish compilation. If running `ngcc` manually after the build, the testing app starts as expected. We will fix the `before-push` script accordingly, thank you.

**@Linting errors**
You mentioned linting errors in `app.po.ts` and `app.e2e-spec.ts`. Running `ng lint @scion/toolkit.e2e` reports success. Could you please provide some more details? Or are you referring to the various linting warnings (not errors) caused by the `@deprecated` tag which is not supported by TSLint? Those errors/warnings will be gone once migrated to ESLint.

**Comment by i7i5** [comment]
Ah ok, yeah I didn't build the thing before the `before-push` command :/
According to the linting-errors: I just pulled the master and ran the `lint` command resulting in ERROR for the files `app.po.ts` and `app.e2e-spec.ts`:

![grafik](https://user-images.githubusercontent.com/9058776/110387327-bf06a980-8061-11eb-9721-271da08c0ffe.png)

BR

**Comment by danielwiehl** [comment]
The linting errors are most likely due to your Git config instructing Git to checkout files in Window style (CRLF), i.e., `core.autocrlf = true`.

We suggest that you set this option to `false` so that Git does not perform any automatic conversions on both, checkout and commit, respectively. If you cloned the repository with `core.autocrlf=true`, you either need to manually convert the line endings back to `LF` or, which is the easier way, set `core.autocrlf` to `false` and clone the repo anew.

Your Git config should look as follows:
```
[core]
	autocrlf = false
```
